CREATE SCHEMA DEMO;

CREATE TABLE "DEMO"."CUSTOMER"(
"CUST_ID" NUMBER(10),
"CUST_NAME" VARCHAR2(50),
PRIMARY KEY (CUST_ID)
);

CREATE TABLE "DEMO"."TRANSACTION"(
"TRANS_ID" NUMBER(10),
"CUST_ID" NUMBER(10),
"TRANS_DATE" DATE,
"TRANS_AMOUNT" DECIMAL(6,2),
PRIMARY KEY (TRANS_ID)
);